# **1. BIBLIOTECAS**

In [33]:
from gspread_dataframe import get_as_dataframe, set_with_dataframe
from datetime import datetime, timezone, timedelta, UTC
from collections import deque
import pandas as pd
import requests
import time
import json
import jwt
import ast
import os

# **2. DADOS DE ACESSO**

## **2.1. Credenciais**

In [34]:
# Salva o JSON em um arquivo
json_content = {
    "_id": "674496ee291c08d0ea882bf5",
    "expiresAt": None,
    "publicKey": "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtzfHy1pbL6+iyjbgJDDM\nYS/e7rLUSUuoZKqL4ekB0j8tvdMjcqPAg6vRReX2vWLmV1ucPDT/S2uIN2FUD7mz\ny7vvxOdykh4V0pF2lq5JTdxsFgNd+Z42gxS8XpZAgQRogKvuuhJLoO1UL4vckqoH\nJdYwFiIqQsMZqWBcOwB5hTdanDE3bUy8HfwQgqB+YFoGS8RS1BF5RePZFAkW6EtJ\n96l/B23jdNTILh5PhRJeEIEI+JpTiM4y6YhZP2Sij218B5x8y4NY3u5d1++Rb+TH\nqbDCgssN6+iCi1coGSXUqkyO6koqHYarmwaJ1wsww8zQJcB2SsFE+g2eepYxB/yt\newIDAQAB\n-----END PUBLIC KEY-----\n",
    "applicationId": "674496ddd6a90d2358276f5f",
    "email": "674496ddd6a90d2358276f5f@sa.dynamox.solutions",
    "privateKey": "-----BEGIN RSA PRIVATE KEY-----\nMIIEpAIBAAKCAQEAtzfHy1pbL6+iyjbgJDDMYS/e7rLUSUuoZKqL4ekB0j8tvdMj\ncqPAg6vRReX2vWLmV1ucPDT/S2uIN2FUD7mzy7vvxOdykh4V0pF2lq5JTdxsFgNd\n+Z42gxS8XpZAgQRogKvuuhJLoO1UL4vckqoHJdYwFiIqQsMZqWBcOwB5hTdanDE3\nbUy8HfwQgqB+YFoGS8RS1BF5RePZFAkW6EtJ96l/B23jdNTILh5PhRJeEIEI+JpT\niM4y6YhZP2Sij218B5x8y4NY3u5d1++Rb+THqbDCgssN6+iCi1coGSXUqkyO6koq\nHYarmwaJ1wsww8zQJcB2SsFE+g2eepYxB/ytewIDAQABAoIBAArpUIXE0M9rN1ex\novGk0lcrYax3i/r9fX7ZRVFj7g7WYmP+sgq+w9VTozf1dRdcT3l+ZDSVt2qHcepS\nao4xMgr9G09vtTwMfKI4tYZNxOHVMb6x3qPiDz8JOhqr+hV07MBU/Pep5UUlPTFD\ntBQr+hb/xYdb64ZkVh/nNDbzVUlgo5VnY2aACFQEhThDXwz2sQBq/VYK6vmoGgx1\nVYv9u4DOhW99BwpKYoF8mwlmeCMPHI43zw0ABO5q9CXaXXH81/0fwHUHebPl0AEr\nyXIGnOGvc1Vt/RLomp/w/1PaYDaNf3tW+Ns/P4VuZHWvD+NfK07ZW5cVQ6mXaMZ4\nLse4GJECgYEA80HsQtBULGkZ444SCYuWqdqSdQucf7IMruk/ppcQqDiF6b4LBzyu\nvZ3W5Z0m5m5nDAEoI2or4mtdft/idNWAtf04k72d2F4S2Jhbmg+W2z/wq3xLHBEk\nNo2l4Z5U8914s9p3HVqwASBIygM4zGrolMLGQOMYuX36SPwgn00igBMCgYEAwNC6\nT1UOJuO5oAPuddvMWWr22dhxwoJjaqvo2zVmesAfCqCoJ6CsDmBTL4eqTPb1nFR+\nw4OjkK1mcBA90E1aghdDVt4FEZCyVgYzLgaBz8vJVkM3K/l7+yXLCOZnZ3ZVIekH\n1l9D47IKK2QWPZ7OrHatLS1bn7Iu26J4orlq2fkCgYEAvJVTyyxkxRUpy97dHudH\ngyB+wByjU9+9s3ACN20Prco8DsyVEiQ6N6gA7Htbp/LZElZnPqVVpi+kCPMaRYcr\nRGsuDGNI1m9/3sim4xXI1uqH8vnl5LlpQJ2phvLPW0tMAuqPw4MFxam4pFvBEcCj\n1If3WGB2T39ZpHFJ/RW4dF8CgYBwlnDz+fp1guvVH/aSI3JDlE3oDpb+uRxMIW2q\n8peQfbaiggUufod5LY3lZxZuMpZgXoZWq/tKc7YpIZK2mzSKWgMcKjBTfWZlDOG9\nslcCe0Bpen4w01Et6XeRDti6dUJotqW464+82S1PAPZrrNuJoRKmGqIxsd3iqhA/\nFH3sIQKBgQDK9ylkNkUFWWl6Y83wLqUOa+lj3B2fYTq75uHwbQFSg4K5o8f4hcOs\nBYCs0R3awgXkeds2Clh+dClqbLpo7Je91BpUaai36iLt02XC/T2qOp8fAL0+V1ij\nP2O0blg85T5QmfyZI6B45tXwVJKsLOcoXgdaLT4xWieErqO/6oyxOA==\n-----END RSA PRIVATE KEY-----\n"
}

with open("application_key.json", "w") as json_file:
    json.dump(json_content, json_file)

## **2.2. URL's**

In [35]:
token_url = "https://api.dynamox.solutions/v1/token"

## **2.3. Token**

### **2.3.1. Requisição de token**

In [36]:
APPLICATION_KEY_PATH = "application_key.json"
URL = token_url

def generate_token(application_key_path: str) -> str:
    with open(application_key_path) as file:
        key = json.load(file)

    return jwt.encode(
      headers={
        "kid": key["_id"],
        "alg": "RS256",
        "typ": "JWT",
      },
      payload={
        "iat": datetime.now(timezone.utc).timestamp(),
        "email": key["email"],
      },
      key=key["privateKey"].encode("utf-8"),
    )

# Gera o token
token = generate_token(APPLICATION_KEY_PATH)
headers = {"Authorization": f"Bearer {token}"}

# Faz a requisição
response = requests.post(url=URL, headers=headers)
data = response.json()

print(data)

{'access_token': 'eyJhbGciOiJSUzI1NiIsImtpZCI6Ijg2OGU0YWNlMGI2NTE2ZDM2YjlmNTZkZThjZTQ5Nzg4ZmNjZGFjNDMiLCJ0eXAiOiJKV1QifQ.eyJuYW1lIjoiU2FtYXJjbyBHZXJtYW5vIC0gTWFpbiBhcHBsaWNhdGlvbiIsImlzcyI6Imh0dHBzOi8vc2VjdXJldG9rZW4uZ29vZ2xlLmNvbS9wcmVkaWN0LXByb2R1Y3Rpb24tcGxhdGZvcm0iLCJhdWQiOiJwcmVkaWN0LXByb2R1Y3Rpb24tcGxhdGZvcm0iLCJhdXRoX3RpbWUiOjE3Nzg2ODgzODgsInVzZXJfaWQiOiJiUnJKcnc2RXJmVGRISXR0UmgzWmg2YnozMEczIiwic3ViIjoiYlJySnJ3NkVyZlRkSEl0dFJoM1poNmJ6MzBHMyIsImlhdCI6MTc3ODY4ODM4OCwiZXhwIjoxNzc4NjkxOTg4LCJlbWFpbCI6IjY3NDQ5NmRkZDZhOTBkMjM1ODI3NmY1ZkBzYS5keW5hbW94LnNvbHV0aW9ucyIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyI2NzQ0OTZkZGQ2YTkwZDIzNTgyNzZmNWZAc2EuZHluYW1veC5zb2x1dGlvbnMiXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.miAPpe0LEx46OMxbYlaclA9nENJnTLSu9I6lR67n6VgoaV2cMhBlvC-4LTbh_m-jpt_Od92Beefq65Au_SZkQc1D5S97zeiSji9LGHh-szzWhbG9rnZFLCZXxEid2vcG_1UxAUFRrI5kKSxvSodDIFtbe2TrXvotNE7ohFo4prbzni-GcdTZeQ0GO73xhCCTi5XGsXrB7rKCNlYHyEZ672sDG5zoNOtZq1djWld_4fC8dVHV-ulvb2-EvGmCtcGVHYpZi7VFnQ97cqi0wLCDci-7Bwk4AsWpkVtCfbd3nv4_GkvzJA45pQ53TPRa5fWwJrVDuIOpEm3XqZ9v1GA1Jg', 'token_type': 'bearer'}

### **2.3.2. Código token**

In [37]:
access_token = data["access_token"]
print(access_token)

eyJhbGciOiJSUzI1NiIsImtpZCI6Ijg2OGU0YWNlMGI2NTE2ZDM2YjlmNTZkZThjZTQ5Nzg4ZmNjZGFjNDMiLCJ0eXAiOiJKV1QifQ.eyJuYW1lIjoiU2FtYXJjbyBHZXJtYW5vIC0gTWFpbiBhcHBsaWNhdGlvbiIsImlzcyI6Imh0dHBzOi8vc2VjdXJldG9rZW4uZ29vZ2xlLmNvbS9wcmVkaWN0LXByb2R1Y3Rpb24tcGxhdGZvcm0iLCJhdWQiOiJwcmVkaWN0LXByb2R1Y3Rpb24tcGxhdGZvcm0iLCJhdXRoX3RpbWUiOjE3Nzg2ODgzODgsInVzZXJfaWQiOiJiUnJKcnc2RXJmVGRISXR0UmgzWmg2YnozMEczIiwic3ViIjoiYlJySnJ3NkVyZlRkSEl0dFJoM1poNmJ6MzBHMyIsImlhdCI6MTc3ODY4ODM4OCwiZXhwIjoxNzc4NjkxOTg4LCJlbWFpbCI6IjY3NDQ5NmRkZDZhOTBkMjM1ODI3NmY1ZkBzYS5keW5hbW94LnNvbHV0aW9ucyIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyI2NzQ0OTZkZGQ2YTkwZDIzNTgyNzZmNWZAc2EuZHluYW1veC5zb2x1dGlvbnMiXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.miAPpe0LEx46OMxbYlaclA9nENJnTLSu9I6lR67n6VgoaV2cMhBlvC-4LTbh_m-jpt_Od92Beefq65Au_SZkQc1D5S97zeiSji9LGHh-szzWhbG9rnZFLCZXxEid2vcG_1UxAUFRrI5kKSxvSodDIFtbe2TrXvotNE7ohFo4prbzni-GcdTZeQ0GO73xhCCTi5XGsXrB7rKCNlYHyEZ672sDG5zoNOtZq1djWld_4fC8dVHV-ulvb2-EvGmCtcGVHYpZi7VFnQ97cqi0wLCDci-7Bwk4AsWpkVtCfbd3nv4_GkvzJA45pQ53TPRa5fWwJrVDuIOpEm3XqZ9v1GA1Jg

## **2.4. Header**

In [30]:
header = {
    "Authorization": f"Bearer {access_token}",
    "Content-Type": "application/json"
}

## **2.5. Workspace**

In [31]:
workspace = {
    "ubu": "62b20314457a4c772a1ba4a8",
    "germano": "62b2031b38d48143feed8ef4"
}

## **2.6. Sheets**

### **2.6.1. Autenticação Sheets**

In [ ]:
import gspread
from google.colab import auth
from gspread_dataframe import set_with_dataframe
from google.auth import default

# Autentica no Google
auth.authenticate_user()

# Usar 'default' para obter as credenciais no formato esperado para o gspread
creds, _ = default()
gc = gspread.authorize(creds)

# **3. HIERARQUIA**

## **3.1. Workspaces**

### **3.1.1. Execução**

In [8]:
headers = header

# Lista filhos de um workspace (com paginação)
def list_children(parent_id):
    children = []
    page_token = None

    while True:
        params = {"parentId": parent_id, "limit": 100}
        if page_token:
            params["pageToken"] = page_token

        r = requests.get(
            "https://api.dynamox.solutions/v1/workspaces",
            headers=headers,
            params=params
        )

        if r.status_code != 200:
            print(f"Erro {r.status_code} para parentId={parent_id}")
            break

        data = r.json()
        children.extend(data.get("docs", []))

        page_token = data.get("items", {}).get("nextPageToken")
        if not page_token:
            break

    return children

# Desce a árvore recursivamente para cada workspace raiz
def traverse(ws_id, ws_name, ancestors=None):
    """
    Retorna lista de dicts com o caminho completo até cada folha.
    """
    if ancestors is None:
        ancestors = []

    current_path = ancestors + [{"id": ws_id, "name": ws_name}]
    children = list_children(ws_id)

    if not children:
        # Folha — nível mais próximo das machines
        return [current_path]

    results = []
    for child in children:
        results.extend(traverse(child["_id"], child["name"], current_path))
    return results

# Executa para cada workspace raiz
all_leaf_paths = {}

for site_name, root_id in workspace.items():
    print(f"\nPercorrendo {site_name} ({root_id})...")
    leaf_paths = traverse(root_id, site_name)
    all_leaf_paths[site_name] = leaf_paths
    print(f"  Folhas encontradas: {len(leaf_paths)}")

Percorrendo ubu (62b20314457a4c772a1ba4a8)...
  Folhas encontradas: 25

Percorrendo germano (62b2031b38d48143feed8ef4)...
  Folhas encontradas: 48

### **3.1.2. Estrutura e organização**

In [9]:
# Converte all_leaf_paths para DataFrame
rows = []

for site_name, leaf_paths in all_leaf_paths.items():
    for path in leaf_paths:
        # Gera uma linha para CADA nível do caminho
        for i in range(len(path)):
            row = {"site": site_name}
            # Preenche os níveis de 0 até i
            for level, ws in enumerate(path[:i+1]):
                row[f"workspace.{level}.id"]   = ws["id"]
                row[f"workspace.{level}.name"] = ws["name"]
            # last = o nível atual (i)
            row["last_workspaceId"]   = path[i]["id"]
            row["last_workspaceName"] = path[i]["name"]
            rows.append(row)

df_workspaces = pd.DataFrame(rows)

# Remove duplicatas — mesmo ws_id pode aparecer em vários caminhos
df_workspaces = df_workspaces.drop_duplicates(subset=["last_workspaceId"])

print(df_workspaces.shape)
display(df_workspaces.head(5))

(107, 15)

,site,workspace.0.id,workspace.0.name,last_workspaceId,last_workspaceName,workspace.1.id,workspace.1.name,workspace.2.id,workspace.2.name,workspace.3.id,workspace.3.name,workspace.4.id,workspace.4.name,workspace.5.id,workspace.5.name
0,ubu,62b20314457a4c772a1ba4a8,ubu,62b20314457a4c772a1ba4a8,ubu,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,ubu,62b20314457a4c772a1ba4a8,ubu,65089b085669ce843f066294,U04 - SALA ELÉTRICA,65089b085669ce843f066294,U04 - SALA ELÉTRICA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,ubu,62b20314457a4c772a1ba4a8,ubu,65eb0b5646f417e7b5199eab,U04-05SB011 - Pelotamento/Forno lV,65089b085669ce843f066294,U04 - SALA ELÉTRICA,65eb0b5646f417e7b5199eab,U04-05SB011 - Pelotamento/Forno lV,NaN,NaN,NaN,NaN,NaN,NaN
3,ubu,62b20314457a4c772a1ba4a8,ubu,65fad3792aced71134d67e0a,Pátio da Subestação,65089b085669ce843f066294,U04 - SALA ELÉTRICA,65eb0b5646f417e7b5199eab,U04-05SB011 - Pelotamento/Forno lV,65fad3792aced71134d67e0a,Pátio da Subestação,NaN,NaN,NaN,NaN
7,ubu,62b20314457a4c772a1ba4a8,ubu,678fc19306ae6b41a15d898c,CCM DISCOS,65089b085669ce843f066294,U04 - SALA ELÉTRICA,65eb0b5646f417e7b5199eab,U04-05SB011 - Pelotamento/Forno lV,678fc19306ae6b41a15d898c,CCM DISCOS,NaN,NaN,NaN,NaN

In [ ]:
# download excel
EXCEL_PATH = "cda_online_dynamox_workspaces.xlsx"
df_workspaces.to_excel(EXCEL_PATH, index=False)

## **3.2. Ativos**

### **3.2.1. Execução**

In [10]:
headers = header

all_assets = []

for workspace_name, workspace_id in workspace.items():
    print(f"\nWorkspace: {workspace_name} ({workspace_id})")

    page = 1

    while True:
        url = f"https://api.dynamox.solutions/v1/workspaces/{workspace_id}/assets?page={page}"

        response = requests.get(url, headers=headers)

        if response.status_code != 200:
            print(f"Erro {response.status_code}")
            break

        data = response.json()

        if not data or "docs" not in data:
            print("Sem dados ou estrutura inesperada")
            break

        docs = data.get("docs", [])

        if docs:
            for d in docs:
                d["workspaceId"] = workspace_id
                d["workspaceName"] = workspace_name
            all_assets.extend(docs)

        # paginação
        if not data.get("pages", {}).get("hasNext", False):
            break

        page += 1

print(f"\nTotal de assets coletados: {len(all_assets)}")

Workspace: ubu (62b20314457a4c772a1ba4a8)

Workspace: germano (62b2031b38d48143feed8ef4)

Total de assets coletados: 585

### **3.2.2. Estrutura e organização**

In [11]:
df_assets = pd.DataFrame(all_assets)

display(df_assets.head(5))

,_id,updatedAt,createdAt,name,parentId,serialNumber,partNumber,code,model,depthAsset,configurationType,workspaceId,workspaceName
0,6a03252df048bc2a543925bc,2026-05-12T13:03:41.146Z,2026-05-12T13:03:41.146Z,TAMBOR DE CALDA TA02,6a0324ba2acc83edcaf16641,,,,conveyorBeltPulley,1,{'assetTypeCategory': 'conveyorPulleyBearing'},62b20314457a4c772a1ba4a8,ubu
1,6a0324ba2acc83edcaf16641,2026-05-12T13:03:41.158Z,2026-05-12T13:01:46.432Z,U03-05TP037,66c373fddb6ca54502de502c,,,,conveyorBeltPulley,0,{'assetTypeCategory': 'conveyorPulleyBearing'},62b20314457a4c772a1ba4a8,ubu
2,69e0dbcc6b4830cc3a9cc497,2026-05-05T13:45:50.858Z,2026-04-16T12:53:32.389Z,Garra de Saida,69e0dbca9ed49fdf0babfafb,,,,None,1,"{'assetRiskClass': None, 'assetType': None}",62b20314457a4c772a1ba4a8,ubu
3,69e0dbcb298d600c67fa2681,2026-05-05T13:46:38.557Z,2026-04-16T12:53:31.316Z,Garra de Entrada,69e0dbca9ed49fdf0babfafb,,,,None,1,{},62b20314457a4c772a1ba4a8,ubu
4,69e0dbca9ed49fdf0babfafb,2026-05-05T13:46:46.114Z,2026-04-16T12:53:30.660Z,U04-07TP007,6890aa4ba752c2a6d8d9982a,,,,None,0,"{'assetRiskClass': None, 'assetType': None}",62b20314457a4c772a1ba4a8,ubu

In [ ]:
# download excel
EXCEL_PATH = "cda_online_dynamox_ativos.xlsx"
df_assets.to_excel(EXCEL_PATH, index=False)

### **3.2.3. Lista de Assets Id**

In [12]:
asset_ids = df_assets.query("depthAsset == 0")["_id"].tolist()

## **3.3. Pontos**

### **3.3.1. Execução**

In [13]:
headers = header

# Cria um df auxiliar só com os assets filtrados
df_assets_filtrado = df_assets[df_assets["_id"].isin(asset_ids)]

all_points = []

for asset_id, workspace_id, workspace_name in zip(
    df_assets_filtrado["_id"],
    df_assets_filtrado["workspaceId"],
    df_assets_filtrado["workspaceName"]
):

    page = 1

    while True:
        url = f"https://api.dynamox.solutions/v1/assets/{asset_id}/monitoring-points?page={page}&limit=100"

        response = requests.get(url, headers=headers)

        if response.status_code != 200:
            print(f"Erro {response.status_code} no asset {asset_id}")
            break

        data = response.json()

        docs = data.get("docs", [])

        if docs:
            for d in docs:
                d["assetId"] = asset_id
                d["workspaceId"] = workspace_id
                d["workspaceName"] = workspace_name

            all_points.extend(docs)

        if not data.get("pages", {}).get("hasNext", False):
            break

        page += 1

print(f"\nTotal de pontos coletados: {len(all_points)}")

Total de pontos coletados: 891

### **3.3.2. Estrutura e organização**

In [14]:
df_points = pd.DataFrame(all_points)

display(df_points.head(5))

,_id,createdAt,name,sensors,spotCharacteristics,updatedAt,parentId,assetId,workspaceId,workspaceName
0,6a0325ca40279d7428c30c21,2026-05-12T13:06:18.285Z,MANCAL LA,"[{'axesOrientation': {'x': 'horizontal', 'y': ...",{'mechanicalSettings': {'rollingBearings': []}...,2026-05-12T13:10:03.222Z,6a03252df048bc2a543925bc,6a0324ba2acc83edcaf16641,62b20314457a4c772a1ba4a8,ubu
1,6a0325e991964eb2ae62ad90,2026-05-12T13:06:49.776Z,MANCAL LOA,"[{'axesOrientation': {'x': 'axial', 'y': 'vert...",{'mechanicalSettings': {'rollingBearings': []}...,2026-05-12T13:13:38.371Z,6a03252df048bc2a543925bc,6a0324ba2acc83edcaf16641,62b20314457a4c772a1ba4a8,ubu
2,69e0dbcdd56587199c6401f1,2026-04-16T12:53:33.781Z,Fase U,[],{'mechanicalSettings': {'rollingBearings': []}...,2026-05-05T13:45:09.830Z,69e0dbcc6b4830cc3a9cc497,69e0dbca9ed49fdf0babfafb,62b20314457a4c772a1ba4a8,ubu
3,69e0dbd6c7a9f6376ec1dcc3,2026-04-16T12:53:42.158Z,Fase V,[],{'mechanicalSettings': {'rollingBearings': []}...,2026-05-05T13:45:29.609Z,69e0dbcc6b4830cc3a9cc497,69e0dbca9ed49fdf0babfafb,62b20314457a4c772a1ba4a8,ubu
4,69e0dbdbac5c94abe878a720,2026-04-16T12:53:47.322Z,Fase W,"[{'axesOrientation': {'x': 'axial', 'y': 'radi...",{'mechanicalSettings': {'rollingBearings': []}...,2026-05-05T13:45:40.307Z,69e0dbcc6b4830cc3a9cc497,69e0dbca9ed49fdf0babfafb,62b20314457a4c772a1ba4a8,ubu

In [ ]:
# download excel
EXCEL_PATH = "cda_online_dynamox_pontos.xlsx"
df_points.to_excel(EXCEL_PATH, index=False)

## **3.3. DataFrame**

In [15]:
# Índices para lookup O(1)
at_idx = df_assets.set_index("_id").to_dict("index")
ws_idx = df_workspaces.set_index("last_workspaceId").to_dict("index")

ws_id_cols   = sorted([c for c in df_workspaces.columns if c.endswith(".id")   and c.startswith("workspace.")])
ws_name_cols = sorted([c for c in df_workspaces.columns if c.endswith(".name") and c.startswith("workspace.")])

def parse_sensors(sensors_raw):
    """Extrai x, y, z do campo sensors (string ou lista)."""
    try:
        if isinstance(sensors_raw, str):
            sensors_raw = ast.literal_eval(sensors_raw)
        if sensors_raw and len(sensors_raw) > 0:
            axes = sensors_raw[0].get("axesOrientation", {})
            return axes.get("x"), axes.get("y"), axes.get("z")
    except Exception:
        pass
    return None, None, None

def subir_hierarquia(point):
    row = {}

    # SPOT (ponto)
    row["spot.id"]        = point.get("_id")
    row["spot.name"]      = point.get("name")
    row["spot.createdAt"] = point.get("createdAt")
    row["spot.updatedAt"] = point.get("updatedAt")
    row["sensor_x"], row["sensor_y"], row["sensor_z"] = parse_sensors(point.get("sensors"))

    # SUBIR PELOS ATIVOS
    # Caso normal:  ponto.parentId → depth1 ou depth2 → depth0
    # Caso especial: ponto.parentId == ponto._id → vai direto pelo assetId (depth0)

    parent_id = point.get("parentId")
    asset_id  = point.get("assetId")

    # Detecta auto-referência (bug na plataforma)
    auto_ref = (parent_id == point.get("_id"))

    depth0 = depth1 = depth2 = None

    if auto_ref:
        # Vai direto para o depth0 via assetId
        depth0 = at_idx.get(asset_id)
    else:
        first_asset = at_idx.get(parent_id)
        if first_asset:
            d = str(first_asset.get("depthAsset", ""))
            if d == "2":
                depth2 = first_asset
                depth2["_id"] = parent_id
                depth1_id = first_asset.get("parentId")
                depth1 = at_idx.get(depth1_id)
                if depth1:
                    depth1["_id"] = depth1_id
                    depth0 = at_idx.get(depth1.get("parentId"))
            elif d == "1":
                depth1 = first_asset
                depth1["_id"] = parent_id
                depth0 = at_idx.get(first_asset.get("parentId"))
            elif d == "0":
                depth0 = first_asset
                depth0["_id"] = parent_id

    # Preenche subset (depth1 ou depth2, o mais próximo do spot)
    subset = depth2 if depth2 else depth1

    if subset:
        row["subset.id"]   = subset.get("_id") or parent_id
        row["subset.name"] = subset.get("name")

    if depth1 and depth2:
        # Tem os dois — guarda depth1 também separado se quiser
        row["component.id"]   = depth1.get("_id")
        row["component.name"] = depth1.get("name")

    # Machine = depth0
    if depth0:
        d0_id = depth0.get("_id") or (at_idx.get(asset_id, {}).get("_id") if auto_ref else None)
        row["machine.id"]              = asset_id if auto_ref else depth1.get("parentId") if depth1 else parent_id
        row["machine.name"]            = depth0.get("name")

        # WORKSPACES
        ws_parent = depth0.get("parentId")
        ws = ws_idx.get(ws_parent)
        if ws:
            row["last_workspaceId"]   = ws_parent
            row["last_workspaceName"] = ws.get("last_workspaceName")
            for col in ws_id_cols + ws_name_cols:
                row[col] = ws.get(col)

    return row

# Aplica para todos os pontos
rows = [subir_hierarquia(p) for p in df_points.to_dict("records")]
df_final = pd.DataFrame(rows)

# Ordena colunas
ws_cols = sorted([c for c in df_final.columns if c.startswith("workspace.")])
ordered = (
    ws_cols
    + ["last_workspaceId", "last_workspaceName"]
    + ["machine.id", "machine.name", "machine.configurationType"]
    + ["subset.id", "subset.name"]
    + ["component.id", "component.name"]
    + ["spot.id", "spot.name"]
    + ["sensor_x", "sensor_y", "sensor_z"]
    + ["spot.createdAt", "spot.updatedAt"]
)
ordered = [c for c in ordered if c in df_final.columns]
df_hierarquia = df_final[ordered]

print(f"Shape: {df_hierarquia.shape}")

# Verifica: quantos spots sem workspace (join falhou)?
sem_ws = df_hierarquia["workspace.0.id"].isna().sum()
print(f"Linhas sem workspace: {sem_ws}")
print()
display(df_hierarquia.head(5))

Shape: (891, 27)
Linhas sem workspace: 1

,workspace.0.id,workspace.0.name,workspace.1.id,workspace.1.name,workspace.2.id,workspace.2.name,workspace.3.id,workspace.3.name,workspace.4.id,workspace.4.name,...,subset.name,component.id,component.name,spot.id,spot.name,sensor_x,sensor_y,sensor_z,spot.createdAt,spot.updatedAt
0,62b20314457a4c772a1ba4a8,ubu,656a04320544926dc6523371,U03 - USINA lll,66c373fddb6ca54502de502c,PELOTAMENTO,NaN,NaN,NaN,NaN,...,TAMBOR DE CALDA TA02,NaN,NaN,6a0325ca40279d7428c30c21,MANCAL LA,horizontal,vertical,axial,2026-05-12T13:06:18.285Z,2026-05-12T13:10:03.222Z
1,62b20314457a4c772a1ba4a8,ubu,656a04320544926dc6523371,U03 - USINA lll,66c373fddb6ca54502de502c,PELOTAMENTO,NaN,NaN,NaN,NaN,...,TAMBOR DE CALDA TA02,NaN,NaN,6a0325e991964eb2ae62ad90,MANCAL LOA,axial,vertical,horizontal,2026-05-12T13:06:49.776Z,2026-05-12T13:13:38.371Z
2,62b20314457a4c772a1ba4a8,ubu,65089b085669ce843f066294,U04 - SALA ELÉTRICA,6890aa4ba752c2a6d8d9982a,U04-07SB012 - Peneiramento 4,NaN,NaN,NaN,NaN,...,Garra de Saida,NaN,NaN,69e0dbcdd56587199c6401f1,Fase U,None,None,None,2026-04-16T12:53:33.781Z,2026-05-05T13:45:09.830Z
3,62b20314457a4c772a1ba4a8,ubu,65089b085669ce843f066294,U04 - SALA ELÉTRICA,6890aa4ba752c2a6d8d9982a,U04-07SB012 - Peneiramento 4,NaN,NaN,NaN,NaN,...,Garra de Saida,NaN,NaN,69e0dbd6c7a9f6376ec1dcc3,Fase V,None,None,None,2026-04-16T12:53:42.158Z,2026-05-05T13:45:29.609Z
4,62b20314457a4c772a1ba4a8,ubu,65089b085669ce843f066294,U04 - SALA ELÉTRICA,6890aa4ba752c2a6d8d9982a,U04-07SB012 - Peneiramento 4,NaN,NaN,NaN,NaN,...,Garra de Saida,NaN,NaN,69e0dbdbac5c94abe878a720,Fase W,axial,radial,horizontal,2026-04-16T12:53:47.322Z,2026-05-05T13:45:40.307Z

In [ ]:
# download excel
EXCEL_PATH = "cda_online_dynamox_hierarquia.xlsx"
df_hierarquia.to_excel(EXCEL_PATH, index=False)

## **3.4. Carga no Sheets**

In [ ]:
# Nome da planilha (precisa já existir no seu Google Drive)
nome_da_planilha = "cda_online_dynamox_hierarquia"
nome_da_aba = "Sheet1"

# Abre a planilha
planilha = gc.open(nome_da_planilha)
aba = planilha.worksheet(nome_da_aba)

# Limpa a aba antes de escrever os dados (opcional)
aba.clear()

# Envia o DataFrame para a aba
set_with_dataframe(aba, df_hierarquia)

print("Dados enviados com sucesso para o Google Sheets!")

# **4. CONDIÇÃO**

## **4.1. Lista de pontos**

In [16]:
spotsid = df_hierarquia["spot.id"].dropna().unique().tolist()

print(f"Total de spots: {len(spotsid)}")

Total de spots: 891

## **4.2. Execução**

In [17]:
all_alert_policies = []

for spotid in spotsid:
    response = requests.get(
        "https://api.dynamox.solutions/v1/alert-policies/status",
        headers=headers,
        params={"resourceId": spotid}
    )

    if response.status_code == 200:
        policies = response.json()  # retorna lista direta
        for policy in policies:
            policy["spotId"] = spotid  # enriquece com o spot
        all_alert_policies.extend(policies)

    elif response.status_code == 429:
        wait = int(response.headers.get("Retry-After", 60))
        print(f"429 → esperando {wait}s")
        time.sleep(wait)
        # re-tenta o mesmo spot
        response = requests.get(
            "https://api.dynamox.solutions/v1/alert-policies/status",
            headers=headers,
            params={"resourceId": spotid}
        )
        if response.status_code == 200:
            policies = response.json()
            for policy in policies:
                policy["spotId"] = spotid
            all_alert_policies.extend(policies)

    else:
        print(f"Erro {response.status_code} no spot {spotid}")

    time.sleep(0.5)

df_alerts = pd.DataFrame(all_alert_policies)

Total de policies: 6308

,policyId,policyName,policyType,currentStatus,lastProcessedAt,spotId
0,6a0326c9084001826c51d59d,TEMPERATURA,telemetry,no-alert,None,6a0325ca40279d7428c30c21
1,6a03280fa7d92476d4c062ae,TEMPERATURA,telemetry,no-alert,None,6a0325e991964eb2ae62ad90
2,69e8d504018f7d31067def5c,Temperatura,telemetry,no-alert,None,69e0dbcdd56587199c6401f1
3,69e8d50c018f7d31067def5d,Temperatura,telemetry,no-alert,None,69e0dbd6c7a9f6376ec1dcc3
4,69e8d515d9021e9a6008d6c5,Temperatura,telemetry,no-alert,None,69e0dbdbac5c94abe878a720

In [22]:
# download excel
EXCEL_PATH = "cda_online_dynamox_condicao.xlsx"
df_alerts.to_excel(EXCEL_PATH, index=False)

## **4.3. DataFrame**

In [43]:
print(f"Total de policies: {len(df_alerts)}")
display(df_alerts.head())

Total de policies: 6308

,policyId,policyName,policyType,currentStatus,lastProcessedAt,spotId
0,6a0326c9084001826c51d59d,TEMPERATURA,telemetry,no-alert,None,6a0325ca40279d7428c30c21
1,6a03280fa7d92476d4c062ae,TEMPERATURA,telemetry,no-alert,None,6a0325e991964eb2ae62ad90
2,69e8d504018f7d31067def5c,Temperatura,telemetry,no-alert,None,69e0dbcdd56587199c6401f1
3,69e8d50c018f7d31067def5d,Temperatura,telemetry,no-alert,None,69e0dbd6c7a9f6376ec1dcc3
4,69e8d515d9021e9a6008d6c5,Temperatura,telemetry,no-alert,None,69e0dbdbac5c94abe878a720

## **4.4. Carga no Sheets**

In [ ]:
# Nome da planilha (precisa já existir no seu Google Drive)
nome_da_planilha = "cda_online_dynamox_condicao"
nome_da_aba = "Sheet1"

# Abre a planilha
planilha = gc.open(nome_da_planilha)
aba = planilha.worksheet(nome_da_aba)

# Limpa a aba antes de escrever os dados (opcional)
aba.clear()

# Envia o DataFrame para a aba
set_with_dataframe(aba, df_alerts)

print("Dados enviados com sucesso para o Google Sheets!")

# **5. LAUDOS**

## **5.1. Execução**

In [ ]:
headers = header

workspaces = workspace

end_date = datetime.now(timezone.utc).replace(hour=0, minute=0, second=0, microsecond=0)
start_date = end_date - timedelta(days=1)

all_reports = []

for name, context_id in workspaces.items():

    print(f"\nWorkspace: {name}")

    params = {
        "contextId": context_id,
        "startAt": start_date.strftime("%Y-%m-%dT%H:%M:%S.000Z"),
        "endAt": (end_date - timedelta(seconds=1)).strftime("%Y-%m-%dT%H:%M:%S.000Z"),
        "sort": "reportedAt",
        "direction": -1,
        "limit": 50,
        "page": 1
    }

    response = requests.get(
        "https://api.dynamox.solutions/v1/technical-reports",
        headers=headers,
        params=params
    )

    print("Status:", response.status_code)

    if response.status_code == 200:
        data = response.json() or {}
        docs = data.get("docs") or []

        if not docs:
            print(f"{name}: sem laudos no período")
        else:
            print(f"{name}: {len(docs)} laudos coletados")
            all_reports.extend(docs)

    elif response.status_code == 429:
        wait = int(response.headers.get("Retry-After", 600))
        print(f"429 → esperando {wait}s")
        time.sleep(wait)

    else:
        print("Erro:", response.text)

    time.sleep(5)

print(f"\nTotal coletado: {len(all_reports)}")

## **5.2. Estrutura e organização**

In [ ]:
def parse_field(val):
    """Converte string de dict/list para objeto Python."""
    if isinstance(val, str):
        try:
            return ast.literal_eval(val)
        except Exception:
            return val
    return val

def processar_laudo(doc):
    row = {
        "component": None,
        "componentId": None,
        "subset": None,
        "subsetId": None,
        "machine": None,
        "machineId": None,
        "spot": None,
        "spotId": None
    }

    # IDs e status
    row["reportId"]   = doc.get("_id")
    row["status"]     = doc.get("alertLevel")
    row["resolution"] = doc.get("status")
    row["type"]       = doc.get("type")
    row["noteNumber"] = doc.get("noteNumber")
    row["statusNote"] = doc.get("statusNote")
    row["deadline"]   = doc.get("deadline")
    row["criticality"]   = doc.get("criticality")
    row["deleted"] = doc.get("deleted")

    # Datas
    row["createdAt"] = doc.get("createdAt")
    row["reportedAt"] = doc.get("reportedAt")
    row["detected"]  = doc.get("detected")
    row["lastUserUpdateAt"] = doc.get("lastUserUpdateAt")
    row["updatedAt"] = doc.get("updatedAt")
    row["deletedAt"]   = doc.get("deletedAt")

    status_history = parse_field(doc.get("statusHistory", {}))
    if isinstance(status_history, dict):
        row["open"]       = status_history.get("open")
        row["inProgress"] = status_history.get("inProgress")
        row["closed"]     = status_history.get("closed")

    # Conteúdo técnico
    row["diagnostic"]   = doc.get("diagnostic")
    row["action"]       = doc.get("action")
    row["observation"]  = doc.get("note")

    # failures é lista → junta em string
    failures = parse_field(doc.get("failures", []))
    if isinstance(failures, list):
        # filtra 'none' e junta
        row["failures"] = ", ".join(f for f in failures if f != "none") or None
    else:
        row["failures"] = failures

    # Criador
    user = parse_field(doc.get("user", {}))
    row["userCreated"] = user.get("name") if isinstance(user, dict) else None

    # Modificador
    user = parse_field(doc.get("lastUpdatedBy", {}))
    row["lastUserUpdated"] = user.get("name") if isinstance(user, dict) else None

    # Hierarquia via breadcrumb
    # breadcrumb: [{"resourceId":..., "name":..., "type": machine|subset|spot}, ...]
    breadcrumb = parse_field(doc.get("breadcrumb", []))
    if isinstance(breadcrumb, list):
        for item in breadcrumb:
            t = item.get("type")
            if t == "machine":
                row["machine"]   = item.get("name")
                row["machineId"] = item.get("resourceId")
            elif t == "subset":
                row["subset"]   = item.get("name")
                row["subsetId"] = item.get("resourceId")
            elif t == "component":
                row["component"]   = item.get("name")
                row["componentId"] = item.get("resourceId")
            elif t == "spot":
                row["spot"]   = item.get("name")
                row["spotId"] = item.get("resourceId")

    return row

# Aplica para todos os laudos coletados
df_laudos = pd.DataFrame([processar_laudo(doc) for doc in all_reports])

# Ordena colunas
ordered = [
    "reportId", "reportedAt",
    "detected", "resolution", "status",
    "open", "inProgress", "closed",
    "machine", "machineId",
    "subset", "subsetId",
    "component", "componentId",
    "spot", "spotId",
    "diagnostic", "failures", "action",
    "noteNumber", "statusNote", "observation",
    "deadline", "criticality",
    "type", "userCreated", "createdAt",
    "lastUserUpdated", "lastUserUpdateAt",
    "deleted", "deletedAt", "updatedAt"
]
ordered = [c for c in ordered if c in df_laudos.columns]
df_laudos = df_laudos[ordered]

print(f"Shape: {df_laudos.shape}")

Shape: (30, 32)

## **5.3. DataFrame**

In [ ]:
display(df_laudos.head(5))

,reportId,reportedAt,detected,resolution,status,open,inProgress,closed,machine,machineId,...,deadline,criticality,type,userCreated,createdAt,lastUserUpdated,lastUserUpdateAt,deleted,deletedAt,updatedAt
0,676058bd98d34406cdf7e62c,2024-12-16T16:43:41.000Z,2024-12-16T04:24:54.000Z,open,a2,2024-12-16T16:43:41.000Z,None,None,U04-07PN002,65e5b866cf996521c951039c,...,None,None,predictive,Schubert Veiga Jeronimo,2024-12-16T16:43:41.831Z,Schubert Veiga Jeronimo,2024-12-16T16:43:41.829Z,False,None,2024-12-16T16:43:41.831Z
1,676016f7f706bd09196d5adc,2024-12-16T12:03:03.000Z,2024-12-16T08:24:32.000Z,open,a2,2024-12-16T12:03:03.000Z,None,None,U04-07PN001,656a15b2aed563060521d2a6,...,None,None,predictive,Schubert Veiga Jeronimo,2024-12-16T12:03:03.949Z,Schubert Veiga Jeronimo,2024-12-16T12:03:03.947Z,False,None,2024-12-16T12:03:03.949Z
2,676016a0f706bd09196d5ad7,2024-12-16T12:01:35.000Z,2024-12-16T08:24:32.000Z,open,a2,2024-12-16T12:01:35.000Z,None,None,U04-07PN001,656a15b2aed563060521d2a6,...,None,None,predictive,Schubert Veiga Jeronimo,2024-12-16T12:01:36.473Z,Schubert Veiga Jeronimo,2024-12-16T12:01:36.471Z,False,None,2024-12-16T12:01:36.473Z
3,66febfb92b9faa24b82569ab,2024-10-03T16:00:56.000Z,2024-10-03T03:00:00.000Z,open,a1,2024-10-03T16:00:56.000Z,None,None,U03-07PN002,66feda2a462ac503f31904b7,...,None,None,predictive,Schubert Veiga Jeronimo,2024-10-03T16:00:57.028Z,Schubert Veiga Jeronimo,2024-10-03T16:00:57.025Z,False,None,2025-04-04T11:39:21.860Z
4,66ec20e7f2b2fa27ed2ed6da,2024-09-19T13:02:30.000Z,2024-09-19T03:00:00.000Z,open,a1,2024-09-19T13:02:30.000Z,None,None,U04-05TP041,67d026ae00c54b69a63a5c98,...,2024-10-18T15:00:00.000Z,None,predictive,Schubert Veiga Jeronimo,2024-09-19T13:02:31.691Z,Schubert Veiga Jeronimo,2024-09-27T13:13:05.201Z,False,None,2025-04-07T19:03:04.879Z

In [ ]:
# download excel
EXCEL_PATH = "cda_online_dynamox_laudos.xlsx"
df_laudos.to_excel(EXCEL_PATH, index=False)

## **5.4. Carga no Sheets**

In [ ]:
# Abre a planilha
nome_da_planilha = "cda_online_dynamox_laudos"
nome_da_aba      = "Sheet1"

planilha = gc.open(nome_da_planilha)
aba      = planilha.worksheet(nome_da_aba)

# Verifica se df_laudos está vazio
if df_laudos.empty:
    print("Nenhum dado novo para processar.")
else:
    # Lê o que já existe na planilha
    dados_existentes = aba.get_all_records()
    df_existente     = pd.DataFrame(dados_existentes)

    if df_existente.empty:
        # Planilha vazia → escreve tudo
        set_with_dataframe(aba, df_laudos)
        print(f"Planilha vazia. {len(df_laudos)} registros inseridos.")

    else:
        novos      = []
        atualizados = 0

        for _, row in df_laudos.iterrows():
            report_id = row["reportId"]
            match     = df_existente[df_existente["reportId"] == report_id]

            if match.empty:
                # ID novo → adiciona
                novos.append(row)

            else:
                # ID existente → compara lastUserUpdateAt
                idx_planilha    = match.index[0]
                update_existente = str(match.iloc[0].get("lastUserUpdateAt", ""))
                update_novo      = str(row.get("lastUserUpdateAt", ""))

                if update_novo != update_existente:
                    # Atualizado → substitui a linha inteira
                    df_existente.loc[idx_planilha] = row
                    atualizados += 1
                # else: duplicata, ignora

        # Adiciona os novos ao df_existente
        if novos:
            df_existente = pd.concat([df_existente, pd.DataFrame(novos)], ignore_index=True)

        # Reescreve a planilha com tudo atualizado
        aba.clear()
        set_with_dataframe(aba, df_existente)

        print(f"Novos inseridos: {len(novos)}")
        print(f"Atualizados: {atualizados}")
        print(f"Total na planilha: {len(df_existente)}")

## **5.5. Rate Limit**

In [ ]:
url = "https://api.dynamox.solutions/v1/technical-reports"

headers = {
    "Authorization": f"Bearer {access_token}"
}

params = {
    "contextId": "62b2031b38d48143feed8ef4",
    "startAt": "2024-06-12T00:00:00.000Z",
    "endAt": "2024-06-12T23:59:59.000Z",
    "limit": 1,
    "page": 1
}

response = requests.get(url, headers=headers, params=params)

print("Status:", response.status_code)

print("\n=== RateLimit-Policy ===")
print(response.headers.get("RateLimit-Policy"))

print("\n=== RateLimit ===")
print(response.headers.get("RateLimit"))

print("\n=== Retry-After ===")
print(response.headers.get("Retry-After"))

print("\n=== BODY ===")
print(response.json())

# **6. TELEMETRIA**

## **6.1. Pontos**

### **6.1.1. Lista de ativos**

In [ ]:
machinelist = ['6890aaa1f3702a4bac37381f', '6890aabdf17babfd7b238b99', '6862af0b4a0902176cf31759', '679785193b33cc5cb6737df3', '6797851f9960697841be5afa', '67a0b263e9e2c6fb27d25f4e', '6862af3ec10fddfc64c4db8d', '6862af51c10fddfc64c4db8e', '6797851ca0e078f5eb9d6ff5', '6862af2c135084dab506fca9', '681a0e3da612598ea8e88677', '65fad3f8155bf676add56ade', '65f4609849d1581201e7c587', '6604254ce5bf4746a9abb972', '65eb0b9846f4172a16199ead', '6862aeb74a0902176cf31758', '6862aea0135084dab506fca8', '6862ae849b05c5c1126bca4a', '6862aee31d45e006fe05ab54']

### **6.1.2. Lista de pontos**

In [ ]:
spotlist = df_hierarquia[df_hierarquia["machine.id"].isin(machinelist)]["spot.id"].tolist()

print(f"Spots: {len(set(spotlist))}")
print(spotlist)

Spots: 115
['6890ac3ac086d74dc457e7ac', '6890ac4d459a13094d0118c6', '6890ac5fbaf642a11fd0198a', '6890ac72f9a37d368e6cb6c3', '6890ac8398002f0dc536597d', '6890ac9893645dac938dac8a', '6890ab5d6bc500f6935a5361', '6890ab6e159d088348ccc7f8', '6890ab806bc500f6935a58e9', '6890ab93f9a37d368e6c8d64', '6890aba66bc500f6935a6307', '6890abb6459a13094d0103e7', '687a4ad438e4a84405462a61', '687a4aff83e77ab84dc4b72e', '687a4b26cc5aa090144a1065', '687a4b4f9cd95d1f3c80c683', '687a4b7b74bc32042f4725cc', '687a4bbfcc5aa090144a33af', '687929116d0383755febf299', '687a47213be02c293c3196f6', '687a4758f61a76d5dedcb70f', '687a47a09cd95d1f3c7dc98e', '687a47f1043fd2247c6eebed', '687a483e6d0383755f3a96af', '6863d963b31585a8f252d76f', '6863d999a31b720f85aaf60d', '6863d9ce77e62cd4219bc06f', '6863d9fb4e989d4fa17fc17e', '6863da25fe641129373cb9d2', '6863da5a2edd46176d5f24e8', '687a44fa9834d52bba0830ba', '687a45619cd95d1f3c7c5bd6', '687a45adda35f49bc2ab2922', '687a45f2479f85763aef7cee', '687a4667043fd2247c6e6636', '687a46a4716e37dc9bb0abcf', '6862b55a2edd46176d0f93ff', '6862b5737d36f609a8aa29e6', '6862b58eb5978507f922ab8c', '6862b5a4b5978507f922adf9', '6862b5bf82cde59a5782c714', '6862b5da98b7baf123713f7c', '6862b1324606298f6df82d60', '6862b497467d5d5955d387a9', '6862b4cb2edd46176d0f768c', '6862b4eb72c4b0762ac2501f', '6862b50718c64153bab4b257', '6862b52a388c55e7d0472fbb', '6862b351881e69282fc839b6', '6862b37277e62cd421502dc2', '6862b392881e69282fc84a5a', '6862b3c3b5978507f92246e6', '6862b3f11486c9d1d0942fdb', '6862b42c82cde59a57824d06', '6862b18bf0647f5e70a049ed', '6862b1cdb125725e61780b63', '6862b1f41c8956bd6dfced69', '6862b22ba2f8d35ba1be23ee', '6862b251b415b01c3c6b5be5', '6862b2cbb125725e617840bf', '681a0fec20d86396098f1c4b', '681a108d86ce3588d47440ba', '681a10bf97702560270d1b9e', '67a0b2f2617f24510ba27dfb', '67a0b36cf2b811bdfed1d032', '67a0b3c10a92218da1f7fbe5', '67a0b48c17bc26bc3fca9a52', '67a0b4cf617f24510ba27f14', '67a0b51659dc6385f0814ef8', '67978837fc293be61cd44d62', '6797883bcd5205872eb29cd0', '6797883f871d12c8f78a1a12', '67978843ee99c2633972f7fc', '67978847fc293be61cd44d75', '67978c391c4f6640a8df5e33', '67978c532bb18ea530aeb4f1', '67978c56c20bc5eb6995a9cb', '67978c5a2810aa61c7803733', '67978c5dfc293be61cd44fe2', '67978c614bda6fe92c005647', '685e97b34e68f60ddcc56f95', '67978c3c658ea54db5e9ddaa', '67978c402810aa61c7803725', '67978c44658ea54db5e9ddb1', '67978c48fbfc0917b45ee6f5', '67978c4c2bb18ea530aeb4e9', '67978c4f96b1c8587c0d45c0', '66042c7d3a730b49bcd4781a', '66042c813b488a46156a087b', '66042c8314dacbcf777b6428', '660430493b488a5f846b48a5', '660436993a730b9a2ad85397', '6604369b6d0687313616eb9a', '6604369d43ddfd16323d1841', '6604369f43ddfd08263d1902', '660436a1f3f0bd19ed3e2221', '66043be9358f543239df0d08', '66043bebf3f0bd4bbe3fc487', '65f46c9cd44de01c858e1454', '65f47077fddd0abab6beb327', '65f4707a06aee973e61b2416', '65f4707c25550ad7903f8eca', '65f4707e4ec104c8d70aa678', '65f470804ec1046aa50aa71d', '65f47567e16d6c3be05f9844', '67b34fb880b7dbc0c97e8b56', '67b34fbc6e72a3aecdd7c8fb', '67b34fc1cd04a20a501c0d41', '67b34fc580b7dbc0c97e8b5f', '65eb172a4f7aed2d7fdafe62', '65eb172cfff6a250299b6d5a', '65eb172e75928a5a3c6e0f2c', '69b5535930b4cca23e550f30', '69b5535cfb8f9d78d1b3c8a3', '69b5536182326b1eec845abc']

## **6.2. Medições**

### **6.2.1. Execução**

In [ ]:
API_URL = "https://api.dynamox.solutions/v1beta/telemetry/data-points/raw"

headers = header

UTC = timezone.utc
hoje = datetime.now(UTC)
ontem = hoje - timedelta(days=1)

# Ontem 00:00 até ontem 23:59:59
from_time = ontem.strftime("%Y-%m-%dT00:00:00Z")
to_time   = ontem.strftime("%Y-%m-%dT23:59:59Z")

# Lista final
telemetry_docs = []

for mp_id in spotlist:
    params = {
        "resourceId": mp_id,
        "fromTime": from_time,
        "toTime": to_time
    }

    url = API_URL
    while url:  # loop para paginação
        response = requests.get(url, headers=headers, params=params)
        params = None  # só manda params na primeira requisição

        if response.status_code == 200:
            data = response.json()

            # Extrair só os campos necessários
            for item in data.get("data", []):
                displayName_pt = item.get("displayName", {}).get("pt")
                attributes_axis = item.get("attributes", {}).get("axis")
                unit = item.get("unit")

                for dp in item.get("dataPoints", []):
                    if displayName_pt and "Temperatura" in displayName_pt:
                        telemetry_docs.append({
                            "monitoringPointId": mp_id,
                            "displayName_pt": displayName_pt,
                            "attributes_axis": attributes_axis,
                            "unit": unit,
                            "dataPoints_datetime": dp.get("datetime"),
                            "dataPoints_value": dp.get("value"),
                        })

            # Verifica se há próxima página
            url = data.get("next")
        else:
            print(f"Erro para o ID {mp_id}: {response.status_code} - {response.text}")
            break

# Exibir resultado final
print(json.dumps(telemetry_docs, indent=2, ensure_ascii=False))

A saída de streaming foi truncada nas últimas 5000 linhas.
    "monitoringPointId": "69b5535930b4cca23e550f30",
    "displayName_pt": "Temperatura",
    "attributes_axis": null,
    "unit": "°C",
    "dataPoints_datetime": "2026-05-05T20:41:19.000Z",
    "dataPoints_value": 29.26718521118164
  },
  {
    "monitoringPointId": "69b5535930b4cca23e550f30",
    "displayName_pt": "Temperatura",
    "attributes_axis": null,
    "unit": "°C",
    "dataPoints_datetime": "2026-05-05T20:46:19.000Z",
    "dataPoints_value": 29.4113826751709
  },
  {
    "monitoringPointId": "69b5535930b4cca23e550f30",
    "displayName_pt": "Temperatura",
    "attributes_axis": null,
    "unit": "°C",
    "dataPoints_datetime": "2026-05-05T20:51:19.000Z",
    "dataPoints_value": 29.614328384399414
  },
  {
    "monitoringPointId": "69b5535930b4cca23e550f30",
    "displayName_pt": "Temperatura",
    "attributes_axis": null,
    "unit": "°C",
    "dataPoints_datetime": "2026-05-05T20:56:19.000Z",
    "dataPoints_value": 29.84931755065918
  },
  {
    "monitoringPointId": "69b5535930b4cca23e550f30",
    "displayName_pt": "Temperatura",
    "attributes_axis": null,
    "unit": "°C",
    "dataPoints_datetime": "2026-05-05T21:01:19.000Z",
    "dataPoints_value": 30.094987869262695
  },
  {
    "monitoringPointId": "69b5535930b4cca23e550f30",
    "displayName_pt": "Temperatura",
    "attributes_axis": null,
    "unit": "°C",
    "dataPoints_datetime": "2026-05-05T21:06:19.000Z",
    "dataPoints_value": 30.40474510192871
  },
  {
    "monitoringPointId": "69b5535930b4cca23e550f30",
    "displayName_pt": "Temperatura",
    "attributes_axis": null,
    "unit": "°C",
    "dataPoints_datetime": "2026-05-05T21:11:19.000Z",
    "dataPoints_value": 30.709163665771484
  },
  {
    "monitoringPointId": "69b5535930b4cca23e550f30",
    "displayName_pt": "Temperatura",
    "attributes_axis": null,
    "unit": "°C",
    "dataPoints_datetime": "2026-05-05T21:16:19.000Z",
    "dataPoints_value": 31.066987991333008
  },
  {
    "monitoringPointId": "69b5535930b4cca23e550f30",
    "displayName_pt": "Temperatura",
    "attributes_axis": null,
    "unit": "°C",
    "dataPoints_datetime": "2026-05-05T21:21:19.000Z",
    "dataPoints_value": 31.47821807861328
  },
  {
    "monitoringPointId": "69b5535930b4cca23e550f30",
    "displayName_pt": "Temperatura",
    "attributes_axis": null,
    "unit": "°C",
    "dataPoints_datetime": "2026-05-05T21:26:19.000Z",
    "dataPoints_value": 31.868085861206055
  },
  {
    "monitoringPointId": "69b5535930b4cca23e550f30",
    "displayName_pt": "Temperatura",
    "attributes_axis": null,
    "unit": "°C",
    "dataPoints_datetime": "2026-05-05T21:31:19.000Z",
    "dataPoints_value": 32.28999710083008
  },
  {
    "monitoringPointId": "69b5535930b4cca23e550f30",
    "displayName_pt": "Temperatura",
    "attributes_axis": null,
    "unit": "°C",
    "dataPoints_datetime": "2026-05-05T21:36:19.000Z",
    "dataPoints_value": 32.74929428100586
  },
  {
    "monitoringPointId": "69b5535930b4cca23e550f30",
    "displayName_pt": "Temperatura",
    "attributes_axis": null,
    "unit": "°C",
    "dataPoints_datetime": "2026-05-05T21:41:19.000Z",
    "dataPoints_value": 33.245975494384766
  },
  {
    "monitoringPointId": "69b5535930b4cca23e550f30",
    "displayName_pt": "Temperatura",
    "attributes_axis": null,
    "unit": "°C",
    "dataPoints_datetime": "2026-05-05T21:41:22.000Z",
    "dataPoints_value": 33.224613189697266
  },
  {
    "monitoringPointId": "69b5535930b4cca23e550f30",
    "displayName_pt": "Temperatura",
    "attributes_axis": null,
    "unit": "°C",
    "dataPoints_datetime": "2026-05-05T21:46:22.000Z",
    "dataPoints_value": 33.8014030456543
  },
  {
    "monitoringPointId": "69b5535930b4cca23e550f30",
    "displayName_pt": "Temperatura",
    "attributes_axis": null,
    "unit": "°C",
    "dataPoints_datetime": "2026-05-05T21:51:22.000Z",
    "dataPoints_value": 34.410240173339844
  },
  {
    "monitoringPointId": "69b5535930b4cca23e550f30",
    "displayName_pt": "Temperatura",
    "attributes_axis": null,
    "unit": "°C",
    "dataPoints_datetime": "2026-05-05T21:56:22.000Z",
    "dataPoints_value": 35.01373291015625
  },
  {
    "monitoringPointId": "69b5535930b4cca23e550f30",
    "displayName_pt": "Temperatura",
    "attributes_axis": null,
    "unit": "°C",
    "dataPoints_datetime": "2026-05-05T22:01:22.000Z",
    "dataPoints_value": 35.6439323425293
  },
  {
    "monitoringPointId": "69b5535930b4cca23e550f30",
    "displayName_pt": "Temperatura",
    "attributes_axis": null,
    "unit": "°C",
    "dataPoints_datetime": "2026-05-05T22:06:22.000Z",
    "dataPoints_value": 36.2047004699707
  },
  {
    "monitoringPointId": "69b5535930b4cca23e550f30",
    "displayName_pt": "Temperatura",
    "attributes_axis": null,
    "unit": "°C",
    "dataPoints_datetime": "2026-05-05T22:11:22.000Z",
    "dataPoints_value": 36.615928649902344
  },
  {
    "monitoringPointId": "69b5535930b4cca23e550f30",
    "displayName_pt": "Temperatura",
    "attributes_axis": null,
    "unit": "°C",
    "dataPoints_datetime": "2026-05-05T22:16:22.000Z",
    "dataPoints_value": 36.904327392578125
  },
  {
    "monitoringPointId": "69b5535930b4cca23e550f30",
    "displayName_pt": "Temperatura",
    "attributes_axis": null,
    "unit": "°C",
    "dataPoints_datetime": "2026-05-05T22:21:22.000Z",
    "dataPoints_value": 37.14999771118164
  },
  {
    "monitoringPointId": "69b5535930b4cca23e550f30",
    "displayName_pt": "Temperatura",
    "attributes_axis": null,
    "unit": "°C",
    "dataPoints_datetime": "2026-05-05T22:26:22.000Z",
    "dataPoints_value": 37.28885269165039
  },
  {
    "monitoringPointId": "69b5535930b4cca23e550f30",
    "displayName_pt": "Temperatura",
    "attributes_axis": null,
    "unit": "°C",
    "dataPoints_datetime": "2026-05-05T22:31:22.000Z",
    "dataPoints_value": 37.43305206298828
  },
  {
    "monitoringPointId": "69b5535930b4cca23e550f30",
    "displayName_pt": "Temperatura",
    "attributes_axis": null,
    "unit": "°C",
    "dataPoints_datetime": "2026-05-05T22:36:22.000Z",
    "dataPoints_value": 37.52918243408203
  },
  {
    "monitoringPointId": "69b5535930b4cca23e550f30",
    "displayName_pt": "Temperatura",
    "attributes_axis": null,
    "unit": "°C",
    "dataPoints_datetime": "2026-05-05T22:41:22.000Z",
    "dataPoints_value": 37.69474411010742
  },
  {
    "monitoringPointId": "69b5535930b4cca23e550f30",
    "displayName_pt": "Temperatura",
    "attributes_axis": null,
    "unit": "°C",
    "dataPoints_datetime": "2026-05-05T22:46:22.000Z",
    "dataPoints_value": 37.95643615722656
  },
  {
    "monitoringPointId": "69b5535930b4cca23e550f30",
    "displayName_pt": "Temperatura",
    "attributes_axis": null,
    "unit": "°C",
    "dataPoints_datetime": "2026-05-05T22:51:22.000Z",
    "dataPoints_value": 38.27687454223633
  },
  {
    "monitoringPointId": "69b5535930b4cca23e550f30",
    "displayName_pt": "Temperatura",
    "attributes_axis": null,
    "unit": "°C",
    "dataPoints_datetime": "2026-05-05T22:56:22.000Z",
    "dataPoints_value": 38.597312927246094
  },
  {
    "monitoringPointId": "69b5535930b4cca23e550f30",
    "displayName_pt": "Temperatura",
    "attributes_axis": null,
    "unit": "°C",
    "dataPoints_datetime": "2026-05-05T23:01:22.000Z",
    "dataPoints_value": 38.88037109375
  },
  {
    "monitoringPointId": "69b5535930b4cca23e550f30",
    "displayName_pt": "Temperatura",
    "attributes_axis": null,
    "unit": "°C",
    "dataPoints_datetime": "2026-05-05T23:06:22.000Z",
    "dataPoints_value": 39.136722564697266
  },
  {
    "monitoringPointId": "69b5535930b4cca23e550f30",
    "displayName_pt": "Temperatura",
    "attributes_axis": null,
    "unit": "°C",
    "dataPoints_datetime": "2026-05-05T23:11:22.000Z",
    "dataPoints_value": 39.328983306884766
  },
  {
    "monitoringPointId": "69b5535930b4cca23e550f30",
    "displayName_pt": "Temperatura",
    "attributes_axis": null,
    "unit": "°C",
    "dataPoints_datetime": "2026-05-05T23:16:22.000Z",
    "dataPoints_value": 39.483863830566406
  },
  {
    "monitoringPointId": "69b5535930b4cca23e550f30",
    "displayName_pt": "Temperatura",
    "attributes_axis": null,
    "unit": "°C",
    "dataPoints_datetime": "2026-05-05T23:21:22.000Z",
    "dataPoints_value": 39.515907287597656
  },
  {
    "monitoringPointId": "69b5535930b4cca23e550f30",
    "displayName_pt": "Temperatura",
    "attributes_axis": null,
    "unit": "°C",
    "dataPoints_datetime": "2026-05-05T23:26:22.000Z",
    "dataPoints_value": 39.537269592285156
  },
  {
    "monitoringPointId": "69b5535930b4cca23e550f30",
    "displayName_pt": "Temperatura",
    "attributes_axis": null,
    "unit": "°C",
    "dataPoints_datetime": "2026-05-05T23:31:22.000Z",
    "dataPoints_value": 39.57465362548828
  },
  {
    "monitoringPointId": "69b5535930b4cca23e550f30",
    "displayName_pt": "Temperatura",
    "attributes_axis": null,
    "unit": "°C",
    "dataPoints_datetime": "2026-05-05T23:36:22.000Z",
    "dataPoints_value": 39.64408493041992
  },
  {
    "monitoringPointId": "69b5535930b4cca23e550f30",
    "displayName_pt": "Temperatura",
    "attributes_axis": null,
    "unit": "°C",
    "dataPoints_datetime": "2026-05-05T23:41:22.000Z",
    "dataPoints_value": 39.70283126831055
  },
  {
    "monitoringPointId": "69b5535930b4cca23e550f30",
    "displayName_pt": "Temperatura",
    "attributes_axis": null,
    "unit": "°C",
    "dataPoints_datetime": "2026-05-05T23:46:22.000Z",
    "dataPoints_value": 39.74555587768555
  },
  {
    "monitoringPointId": "69b5535930b4cca23e550f30",
    "displayName_pt": "Temperatura",
    "attributes_axis": null,
    "unit": "°C",
    "dataPoints_datetime": "2026-05-05T23:51:22.000Z",
    "dataPoints_value": 39.80964279174805
  },
  {
    "monitoringPointId": "69b5535930b4cca23e550f30",
    "displayName_pt": "Temperatura",
    "attributes_axis": null,
    "unit": "°C",
    "dataPoints_datetime": "2026-05-05T23:56:22.000Z",
    "dataPoints_value": 39.85770797729492
  },
  {
    "monitoringPointId": "69b5535cfb8f9d78d1b3c8a3",
    "displayName_pt": "Temperatura",
    "attributes_axis": null,
    "unit": "°C",
    "dataPoints_datetime": "2026-05-05T00:04:28.000Z",
    "dataPoints_value": 50.31471633911133
  },
  {
    "monitoringPointId": "69b5535cfb8f9d78d1b3c8a3",
    "displayName_pt": "Temperatura",
    "attributes_axis": null,
    "unit": "°C",
    "dataPoints_datetime": "2026-05-05T00:09:28.000Z",
    "dataPoints_value": 50.35744094848633
  },
  {
    "monitoringPointId": "69b5535cfb8f9d78d1b3c8a3",
    "displayName_pt": "Temperatura",
    "attributes_axis": null,
    "unit": "°C",
    "dataPoints_datetime": "2026-05-05T00:14:28.000Z",
    "dataPoints_value": 50.41619110107422
  },
  {
    "monitoringPointId": "69b5535cfb8f9d78d1b3c8a3",
    "displayName_pt": "Temperatura",
    "attributes_axis": null,
    "unit": "°C",
    "dataPoints_datetime": "2026-05-05T00:19:28.000Z",
    "dataPoints_value": 50.442893981933594
  },
  {
    "monitoringPointId": "69b5535cfb8f9d78d1b3c8a3",
    "displayName_pt": "Temperatura",
    "attributes_axis": null,
    "unit": "°C",
    "dataPoints_datetime": "2026-05-05T00:24:28.000Z",
    "dataPoints_value": 50.53368377685547
  },
  {
    "monitoringPointId": "69b5535cfb8f9d78d1b3c8a3",
    "displayName_pt": "Temperatura",
    "attributes_axis": null,
    "unit": "°C",
    "dataPoints_datetime": "2026-05-05T00:29:28.000Z",
    "dataPoints_value": 50.60845184326172
  },
  {
    "monitoringPointId": "69b5535cfb8f9d78d1b3c8a3",
    "displayName_pt": "Temperatura",
    "attributes_axis": null,
    "unit": "°C",
    "dataPoints_datetime": "2026-05-05T00:34:28.000Z",
    "dataPoints_value": 50.69924545288086
  },
  {
    "monitoringPointId": "69b5535cfb8f9d78d1b3c8a3",
    "displayName_pt": "Temperatura",
    "attributes_axis": null,
    "unit": "°C",
    "dataPoints_datetime": "2026-05-05T00:39:28.000Z",
    "dataPoints_value": 50.77401351928711
  },
  {
    "monitoringPointId": "69b5535cfb8f9d78d1b3c8a3",
    "displayName_pt": "Temperatura",
    "attributes_axis": null,
    "unit": "°C",
    "dataPoints_datetime": "2026-05-05T00:39:53.000Z",
    "dataPoints_value": 50.779354095458984
  },
  {
    "monitoringPointId": "69b5535cfb8f9d78d1b3c8a3",
    "displayName_pt": "Temperatura",
    "attributes_axis": null,
    "unit": "°C",
    "dataPoints_datetime": "2026-05-05T00:44:53.000Z",
    "dataPoints_value": 50.85946273803711
  },
  {
    "monitoringPointId": "69b5535cfb8f9d78d1b3c8a3",
    "displayName_pt": "Temperatura",
    "attributes_axis": null,
    "unit": "°C",
    "dataPoints_datetime": "2026-05-05T00:49:53.000Z",
    "dataPoints_value": 50.90753173828125
  },
  {
    "monitoringPointId": "69b5535cfb8f9d78d1b3c8a3",
    "displayName_pt": "Temperatura",
    "attributes_axis": null,
    "unit": "°C",
    "dataPoints_datetime": "2026-05-05T00:54:53.000Z",
    "dataPoints_value": 51.01434326171875
  },
  {
    "monitoringPointId": "69b5535cfb8f9d78d1b3c8a3",
    "displayName_pt": "Temperatura",
    "attributes_axis": null,
    "unit": "°C",
    "dataPoints_datetime": "2026-05-05T00:59:53.000Z",
    "dataPoints_value": 51.14786148071289
  },
  {
    "monitoringPointId": "69b5535cfb8f9d78d1b3c8a3",
    "displayName_pt": "Temperatura",
    "attributes_axis": null,
    "unit": "°C",
    "dataPoints_datetime": "2026-05-05T01:04:53.000Z",
    "dataPoints_value": 51.25467300415039
  },
  {
    "monitoringPointId": "69b5535cfb8f9d78d1b3c8a3",
    "displayName_pt": "Temperatura",
    "attributes_axis": null,
    "unit": "°C",
    "dataPoints_datetime": "2026-05-05T01:09:53.000Z",
    "dataPoints_value": 51.249332427978516
  },
  {
    "monitoringPointId": "69b5535cfb8f9d78d1b3c8a3",
    "displayName_pt": "Temperatura",
    "attributes_axis": null,
    "unit": "°C",
    "dataPoints_datetime": "2026-05-05T01:14:53.000Z",
    "dataPoints_value": 51.25467300415039
  },
  {
    "monitoringPointId": "69b5535cfb8f9d78d1b3c8a3",
    "displayName_pt": "Temperatura",
    "attributes_axis": null,
    "unit": "°C",
    "dataPoints_datetime": "2026-05-05T01:19:53.000Z",
    "dataPoints_value": 51.270694732666016
  },
  {
    "monitoringPointId": "69b5535cfb8f9d78d1b3c8a3",
    "displayName_pt": "Temperatura",
    "attributes_axis": null,
    "unit": "°C",
    "dataPoints_datetime": "2026-05-05T01:24:53.000Z",
    "dataPoints_value": 51.292057037353516
  },
  {
    "monitoringPointId": "69b5535cfb8f9d78d1b3c8a3",
    "displayName_pt": "Temperatura",
    "attributes_axis": null,
    "unit": "°C",
    "dataPoints_datetime": "2026-05-05T01:29:53.000Z",
    "dataPoints_value": 51.29739761352539
  },
  {
    "monitoringPointId": "69b5535cfb8f9d78d1b3c8a3",
    "displayName_pt": "Temperatura",
    "attributes_axis": null,
    "unit": "°C",
    "dataPoints_datetime": "2026-05-05T01:34:53.000Z",
    "dataPoints_value": 51.35080337524414
  },
  {
    "monitoringPointId": "69b5535cfb8f9d78d1b3c8a3",
    "displayName_pt": "Temperatura",
    "attributes_axis": null,
    "unit": "°C",
    "dataPoints_datetime": "2026-05-05T01:39:53.000Z",
    "dataPoints_value": 51.40955352783203
  },
  {
    "monitoringPointId": "69b5535cfb8f9d78d1b3c8a3",
    "displayName_pt": "Temperatura",
    "attributes_axis": null,
    "unit": "°C",
    "dataPoints_datetime": "2026-05-05T01:44:53.000Z",
    "dataPoints_value": 51.47364044189453
  },
  {
    "monitoringPointId": "69b5535cfb8f9d78d1b3c8a3",
    "displayName_pt": "Temperatura",
    "attributes_axis": null,
    "unit": "°C",
    "dataPoints_datetime": "2026-05-05T01:49:53.000Z",
    "dataPoints_value": 51.52704620361328
  },
  {
    "monitoringPointId": "69b5535cfb8f9d78d1b3c8a3",
    "displayName_pt": "Temperatura",
    "attributes_axis": null,
    "unit": "°C",
    "dataPoints_datetime": "2026-05-05T01:54:53.000Z",
    "dataPoints_value": 51.53772735595703
  },
  {
    "monitoringPointId": "69b5535cfb8f9d78d1b3c8a3",
    "displayName_pt": "Temperatura",
    "attributes_axis": null,
    "unit": "°C",
    "dataPoints_datetime": "2026-05-05T01:59:53.000Z",
    "dataPoints_value": 51.585792541503906
  },
  {
    "monitoringPointId": "69b5535cfb8f9d78d1b3c8a3",
    "displayName_pt": "Temperatura",
    "attributes_axis": null,
    "unit": "°C",
    "dataPoints_datetime": "2026-05-05T02:04:53.000Z",
    "dataPoints_value": 51.60181427001953
  },
  {
    "monitoringPointId": "69b5535cfb8f9d78d1b3c8a3",
    "displayName_pt": "Temperatura",
    "attributes_axis": null,
    "unit": "°C",
    "dataPoints_datetime": "2026-05-05T02:09:53.000Z",
    "dataPoints_value": 51.68192672729492
  },
  {
    "monitoringPointId": "69b5535cfb8f9d78d1b3c8a3",
    "displayName_pt": "Temperatura",
    "attributes_axis": null,
    "unit": "°C",
    "dataPoints_datetime": "2026-05-05T02:14:53.000Z",
    "dataPoints_value": 51.69260787963867
  },
  {
    "monitoringPointId": "69b5535cfb8f9d78d1b3c8a3",
    "displayName_pt": "Temperatura",
    "attributes_axis": null,
    "unit": "°C",
    "dataPoints_datetime": "2026-05-05T02:19:53.000Z",
    "dataPoints_value": 51.70328903198242
  },
  {
    "monitoringPointId": "69b5535cfb8f9d78d1b3c8a3",
    "displayName_pt": "Temperatura",
    "attributes_axis": null,
    "unit": "°C",
    "dataPoints_datetime": "2026-05-05T02:24:53.000Z",
    "dataPoints_value": 51.68192672729492
  },
  {
    "monitoringPointId": "69b5535cfb8f9d78d1b3c8a3",
    "displayName_pt": "Temperatura",
    "attributes_axis": null,
    "unit": "°C",
    "dataPoints_datetime": "2026-05-05T02:29:53.000Z",
    "dataPoints_value": 51.62852096557617
  },
  {
    "monitoringPointId": "69b5535cfb8f9d78d1b3c8a3",
    "displayName_pt": "Temperatura",
    "attributes_axis": null,
    "unit": "°C",
    "dataPoints_datetime": "2026-05-05T02:34:53.000Z",
    "dataPoints_value": 51.564430236816406
  },
  {
    "monitoringPointId": "69b5535cfb8f9d78d1b3c8a3",
    "displayName_pt": "Temperatura",
    "attributes_axis": null,
    "unit": "°C",
    "dataPoints_datetime": "2026-05-05T02:39:53.000Z",
    "dataPoints_value": 51.40955352783203
  },
  {
    "monitoringPointId": "69b5535cfb8f9d78d1b3c8a3",
    "displayName_pt": "Temperatura",
    "attributes_axis": null,
    "unit": "°C",
    "dataPoints_datetime": "2026-05-05T02:44:53.000Z",
    "dataPoints_value": 51.23331069946289
  },
  {
    "monitoringPointId": "69b5535cfb8f9d78d1b3c8a3",
    "displayName_pt": "Temperatura",
    "attributes_axis": null,
    "unit": "°C",
    "dataPoints_datetime": "2026-05-05T02:49:53.000Z",
    "dataPoints_value": 50.99298095703125
  },
  {
    "monitoringPointId": "69b5535cfb8f9d78d1b3c8a3",
    "displayName_pt": "Temperatura",
    "attributes_axis": null,
    "unit": "°C",
    "dataPoints_datetime": "2026-05-05T02:54:53.000Z",
    "dataPoints_value": 50.73128890991211
  },
  {
    "monitoringPointId": "69b5535cfb8f9d78d1b3c8a3",
    "displayName_pt": "Temperatura",
    "attributes_axis": null,
    "unit": "°C",
    "dataPoints_datetime": "2026-05-05T02:59:53.000Z",
    "dataPoints_value": 50.51232147216797
  },
  {
    "monitoringPointId": "69b5535cfb8f9d78d1b3c8a3",
    "displayName_pt": "Temperatura",
    "attributes_axis": null,
    "unit": "°C",
    "dataPoints_datetime": "2026-05-05T03:04:53.000Z",
    "dataPoints_value": 50.27199172973633
  },
  {
    "monitoringPointId": "69b5535cfb8f9d78d1b3c8a3",
    "displayName_pt": "Temperatura",
    "attributes_axis": null,
    "unit": "°C",
    "dataPoints_datetime": "2026-05-05T03:09:53.000Z",
    "dataPoints_value": 50.02632141113281
  },
  {
    "monitoringPointId": "69b5535cfb8f9d78d1b3c8a3",
    "displayName_pt": "Temperatura",
    "attributes_axis": null,
    "unit": "°C",
    "dataPoints_datetime": "2026-05-05T03:14:53.000Z",
    "dataPoints_value": 49.83939743041992
  },
  {
    "monitoringPointId": "69b5535cfb8f9d78d1b3c8a3",
    "displayName_pt": "Temperatura",
    "attributes_axis": null,
    "unit": "°C",
    "dataPoints_datetime": "2026-05-05T03:19:53.000Z",
    "dataPoints_value": 49.70054244995117
  },

### **6.2.2. Estrutura e organização**

In [ ]:
df_telemetry = pd.DataFrame(telemetry_docs)

# Lista com os nomes das colunas que você quer manter
colunas_desejadas = ["monitoringPointId", "attributes_axis", "displayName_pt", "unit", "dataPoints_value", "dataPoints_datetime"]

# Verifica se o DataFrame não está vazio e contém as colunas desejadas
if not df_telemetry.empty and all(col in df_telemetry.columns for col in colunas_desejadas):
    df_telemetry = df_telemetry[colunas_desejadas]
    display(df_telemetry)
else:
    print("DataFrame vazio ou colunas desejadas não estão presentes.")
    df_telemetry = pd.DataFrame(columns=colunas_desejadas)

,monitoringPointId,attributes_axis,displayName_pt,unit,dataPoints_value,dataPoints_datetime
0,6890ab5d6bc500f6935a5361,None,Temperatura,°C,36.583885,2026-01-11T00:02:26.000Z
1,6890ab5d6bc500f6935a5361,None,Temperatura,°C,36.621269,2026-01-11T00:12:26.000Z
2,6890ab5d6bc500f6935a5361,None,Temperatura,°C,36.663998,2026-01-11T00:22:26.000Z
3,6890ab5d6bc500f6935a5361,None,Temperatura,°C,36.685360,2026-01-11T00:32:26.000Z
4,6890ab5d6bc500f6935a5361,None,Temperatura,°C,36.722744,2026-01-11T00:42:26.000Z
...,...,...,...,...,...,...
52635,6862b5da98b7baf123713f7c,None,Temperatura,°C,40.995270,2026-01-13T17:02:18.000Z
52636,6862b5da98b7baf123713f7c,None,Temperatura,°C,40.984589,2026-01-13T17:12:18.000Z
52637,6862b5da98b7baf123713f7c,None,Temperatura,°C,40.957886,2026-01-13T17:22:18.000Z
52638,6862b5da98b7baf123713f7c,None,Temperatura,°C,40.995270,2026-01-13T17:32:18.000Z
52639,6862b5da98b7baf123713f7c,None,Temperatura,°C,40.995270,2026-01-13T17:42:18.000Z

### **6.2.3. DataFrame**

In [ ]:
display(df_telemetry)

### **6.2.4. Carga no Sheets**

In [ ]:
# Nome da planilha e aba
nome_da_planilha = "cda_online_dynamox_telemetria"
nome_da_aba = "Sheet1"

# Abre a planilha e a aba
planilha = gc.open(nome_da_planilha)
aba = planilha.worksheet(nome_da_aba)

# Lê os valores atuais da aba
dados_existentes = aba.get_all_values()

# Converte para DataFrame (se houver dados)
if dados_existentes:
    df_existente = pd.DataFrame(dados_existentes[1:], columns=dados_existentes[0])  # ignora cabeçalho
else:
    df_existente = pd.DataFrame()

# Prepara o novo DataFrame (df_telemetry precisa já estar criado antes)
df_novo = df_telemetry.copy()

# Converte colunas complexas (dicionários, listas) para string
for col in df_novo.select_dtypes(include=["object"]).columns:
    df_novo[col] = df_novo[col].apply(lambda x: json.dumps(x) if isinstance(x, (dict, list)) else x)

# Define as colunas para comparação de duplicados
chaves = ["monitoringPointId", "attributes_axis", "displayName_pt", "unit", "dataPoints_value", "dataPoints_datetime"]

# Se já houver dados existentes, remover duplicados
if not df_existente.empty:
    # Garante que todas as colunas existem nos dois DataFrames
    colunas_comuns = [c for c in chaves if c in df_existente.columns and c in df_novo.columns]
    # Cria um conjunto de tuplas com as combinações já existentes
    existentes_set = set(df_existente[colunas_comuns].apply(tuple, axis=1).tolist())
    # Filtra os novos dados mantendo apenas combinações não existentes
    df_filtrado = df_novo[~df_novo[colunas_comuns].apply(tuple, axis=1).isin(existentes_set)]
else:
    df_filtrado = df_novo.copy()

# Se for a primeira vez, adiciona os cabeçalhos
if not dados_existentes:
    aba.append_row(df_filtrado.columns.tolist())

# Adiciona somente os dados novos
if not df_filtrado.empty:
    aba.append_rows(df_filtrado.values.tolist(), value_input_option="RAW")
    print(f"{len(df_filtrado)} novas linhas adicionadas com sucesso.")
else:
    print("Nenhuma nova linha para adicionar. Tudo já está na planilha.")

✅ 52640 novas linhas adicionadas com sucesso.

### **6.2.5. Remoção de Duplicadas**

In [ ]:
nome_da_planilha = "cda_online_dynamox_telemetria"
nome_da_aba = "Sheet1"
chaves = ["monitoringPointId", "attributes_axis", "displayName_pt", "unit", "dataPoints_value", "dataPoints_datetime"]

planilha = gc.open(nome_da_planilha)
aba = planilha.worksheet(nome_da_aba)
dados_existentes = aba.get_all_values()

if not dados_existentes:
    print("A planilha está vazia. Nada a verificar.")
else:
    # Converte para DataFrame
    df = pd.DataFrame(dados_existentes[1:], columns=dados_existentes[0])
    linhas_antes = len(df)

    # Remove duplicados (mantém a primeira ocorrência)
    df_sem_dup = df.drop_duplicates(subset=chaves, keep="first")
    linhas_depois = len(df_sem_dup)

    # Se houve duplicação
    if linhas_depois < linhas_antes:
        # Limpa a planilha
        aba.clear()
        # Reescreve cabeçalho
        aba.append_row(df_sem_dup.columns.tolist())
        # Reescreve dados limpos
        aba.append_rows(df_sem_dup.values.tolist(), value_input_option="RAW")
        print(f"Removidas {linhas_antes - linhas_depois} linhas duplicadas. Planilha atualizada com sucesso.")
    else:
        print("Nenhuma duplicação encontrada. Tudo limpo.")

✅ Removidas 57 linhas duplicadas. Planilha atualizada com sucesso.

# **7. PSEUDOCÓDIGO**

# CDA Online Dynamox

---

## 1. CONFIGURAÇÕES INICIAIS

```
SALVAR em "application_key.json":
    { _id, expiresAt, publicKey, applicationId, email, privateKey }

DEFINIR:
    token_url = "https://api.dynamox.solutions/v1/token"

workspace = {
    "ubu"     : "62b20314457a4c772a1ba4a8",
    "germano" : "62b2031b38d48143feed8ef4"
}

AUTENTICAR Google Sheets via OAuth
```

---

## 2. AUTENTICAÇÃO

```
FUNÇÃO generate_token(application_key_path):
    ler chave JSON
    gerar JWT RSA-256
    RETORNAR token

token = generate_token("application_key.json")

POST token_url com Bearer token
access_token = resposta["access_token"]

headers = {
    Authorization: "Bearer {access_token}",
    Content-Type: "application/json"
}
```

---

## 3. HIERARQUIA

### 3.1 WORKSPACES

```
FUNÇÃO list_children(parent_id):
    children = []
    page_token = NULL

    LOOP:
        GET /v1/workspaces com parentId

        SE erro:
            registrar
            SAIR

        adicionar docs em children

        SE nextPageToken inexistente:
            SAIR

    RETORNAR children


FUNÇÃO traverse(ws_id, ws_name, ancestors=[]):
    current_path = ancestors + workspace atual
    children = list_children(ws_id)

    SE children vazio:
        RETORNAR current_path

    PARA CADA child:
        traverse(child)

EXECUTAR traverse para cada workspace raiz

GERAR df_workspaces
REMOVER duplicatas
SALVAR Excel
```

---

### 3.2 ASSETS

```
PARA CADA workspace:
    LOOP paginado:
        GET /v1/workspaces/{workspace_id}/assets

        SE erro:
            registrar
            SAIR

        adicionar assets

FILTRAR depthAsset == 0
GERAR df_assets
SALVAR Excel
```

---

### 3.3 PONTOS DE MONITORAMENTO

```
PARA CADA asset raiz:
    LOOP paginado:
        GET /v1/assets/{asset_id}/monitoring-points

        SE erro:
            registrar
            SAIR

        adicionar pontos

GERAR df_points
SALVAR Excel
```

---

### 3.4 HIERARQUIA COMPLETA

```
FUNÇÃO parse_sensors():
    extrair orientação x/y/z

FUNÇÃO subir_hierarquia(point):
    montar:
        workspace
        machine
        component
        subset
        spot
        sensores
        timestamps

    tratar auto-referência do parentId

    RETORNAR row

CRIAR índices lookup:
    at_idx
    ws_idx

APLICAR subir_hierarquia para todos os pontos

GERAR df_hierarquia
SALVAR Excel
ENVIAR Google Sheets
```

---

## 4. CONDIÇÃO

```
### 4.1 LISTA DE PONTOS

spotsid = df_hierarquia["spot.id"]

REMOVER nulos
REMOVER duplicados
```

---

### 4.2 CONSULTA STATUS DE ALERTA

```
all_alert_policies = []

PARA CADA spotid:
    GET /v1/alert-policies/status?resourceId=spotid

    SE status 200:
        policies = resposta
        adicionar spotId em cada policy
        adicionar em all_alert_policies

    SENÃO SE status 429:
        aguardar Retry-After
        repetir requisição

    SENÃO:
        registrar erro

    aguardar pequeno intervalo entre chamadas
```

---

### 4.3 DATAFRAME CONDIÇÃO

```
df_alerts = DataFrame(all_alert_policies)

VALIDAR:
    quantidade total
    preview dos registros

SALVAR:
    cda_online_dynamox_condicao.xlsx
```

---

### 4.4 CARGA GOOGLE SHEETS

```
ABRIR planilha:
    cda_online_dynamox_condicao

LIMPAR aba
ESCREVER df_alerts
```

---

## 5. TELEMETRIA

### 5.1 LISTA DE PONTOS

```
machinelist = lista fixa de máquinas

spotlist =
    df_hierarquia
    filtrar machine.id em machinelist
    extrair spot.id
```

---

### 5.2 COLETA DE TELEMETRIA

```
PARA CADA spot:
    GET /v1beta/telemetry/data-points/raw

    LOOP paginação:
        processar resposta

        SE displayName contém "Temperatura":
            salvar:
                monitoringPointId
                axis
                unidade
                datetime
                valor
```

---

### 5.3 DATAFRAME

```
GERAR df_telemetry

SE vazio:
    criar dataframe padrão
```

---

### 5.4 CARGA INCREMENTAL

```
ABRIR Google Sheets telemetria

LER registros existentes

COMPARAR por chave:
    monitoringPointId
    attributes_axis
    displayName_pt
    unit
    dataPoints_value
    dataPoints_datetime

INSERIR somente novos
```

---

### 5.5 REMOVER DUPLICATAS

```
LER planilha completa
REMOVER duplicados
REESCREVER
```

---

## 6. LAUDOS

### 6.1 CONSULTA

```
PARA CADA workspace:
    GET /v1/technical-reports

    SE 200:
        armazenar docs

    SE 429:
        aguardar Retry-After
```

---

### 6.2 PROCESSAMENTO

```
FUNÇÃO processar_laudo(doc):
    extrair:
        identificação
        status
        datas
        falhas
        usuários
        breadcrumb
        machine/component/subset/spot

RETORNAR row

GERAR df_laudos
SALVAR Excel
```

---

### 6.3 UPSERT GOOGLE SHEETS

```
SE planilha vazia:
    inserir tudo

SENÃO:
    comparar por reportId

    SE novo:
        inserir

    SE atualizado:
        substituir

REESCREVER planilha
```

---

## 7. RATE LIMIT

```
CONSULTAR endpoint teste

EXIBIR:
    RateLimit-Policy
    RateLimit
    Retry-After

VALIDAR comportamento histórico
```

---

## FLUXO GERAL

```
INÍCIO
│
├─ Autenticação API
├─ Hierarquia
│   ├─ Workspaces
│   ├─ Assets
│   ├─ Pontos
│   └─ Hierarquia consolidada
│
├─ Condição
│   ├─ Buscar status alert-policies
│   ├─ Consolidar dataframe
│   └─ Enviar Sheets
│
├─ Telemetria
│   ├─ Buscar temperatura
│   ├─ Incremental
│   └─ Deduplicação
│
├─ Laudos
│   ├─ Consulta
│   ├─ Processamento
│   └─ Upsert
│
└─ Diagnóstico Rate Limit

FIM
```